### ISSUE TITLE
json.decoder.JSONDecodeError while generating PDF

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/badgeyay#130]
**I'm submitting a ...**
- [x] bug report
- [ ] feature request

**Current behavior:**
Getting error when generating pdf

**Expected behavior:**
Should generate pdf

**Steps to reproduce:**
1. Open `http://127.0.0.1:5000/`
2. Select csv file from samples
3. Enter Eventyay url
4. Click upload and error reproduced

Error log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/run/media/vaibhav/New Volume/My Projects/Fossasia/badgeyay/app/main.py", line 91, in upload
    generate_csv_eventyay.tocsv(eventyay_url,filename)
  File "/run/media/vaibhav/New Volume/My Projects/Fossasia/badgeyay/app/generate_csv_eventyay.py", line 15, in tocsv
    data = json.loads(url.read().decode(url.info().get_param('charset') or 'utf8'))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Yes, I am interested in working on this issue**

**Comment by pushkalkatara** [comment]
Why do you want to select URL with CSV? When you enter EventYay URL, basically its the RESTFUL API's URL, which is a json result with the details of speakers or anything requested. Using this JSON data, it generates the CSV file, and print the PDF.

**Comment by jajodiaraghav** [comment]
I think, the best way to fix this would be to throw an error in case the user uploads a file along with filling the Eventyay URL field.

In case the Eventyay URL field is a standalone field, This could be specified on the label of the field.

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav Will send PR 😄

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 Please update your status on this

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I am really sorry, i don't know how i skipped this will send PR by EOD

**Comment by jajodiaraghav** [comment]
@vaibhavsingh97 You claimed the issue and never sent a PR. Are you working on it? or should the issue be make public for claiming?
Now that you are a maintainer, it is your responsibility as well to see the progress in not blocked.

**Comment by vaibhavsingh97** [comment]
@jajodiaraghav I tried to reroduce the problem but it's not reproducable so I think we can close this issue. What are your opinion on this?

**Comment by jajodiaraghav** [comment]
Closing this. We can reopen if the issue persists.
